export interface Script {
  chart: ScriptChartItem[];
  symbols: ScriptSymbol[];
  keyboard: ScriptKeyboard;
}

export interface ScriptChartItem {
  consonant: string | null;
  chars: [
    string | null,
    string | null,
    string | null,
    string | null,
    string | null
  ];
}

export interface ScriptSymbol {
  char: string;
  romaji: string;
  set: "base" | "dakuten" | "double";
  group: string;
}

export type ScriptKeyboard = Record<string, string>;

export const Hiragana: Script = {
  chart: [
    { consonant: null, chars: ["あ", "い", "う", "え", "お"] },
    { consonant: "k", chars: ["か", "き", "く", "け", "こ"] },
    { consonant: "s", chars: ["さ", "し", "す", "せ", "そ"] },
    { consonant: "t", chars: ["た", "ち", "つ", "て", "と"] },
    { consonant: "n", chars: ["な", "に", "ぬ", "ね", "の"] },
    { consonant: "h", chars: ["は", "ひ", "ふ", "へ", "ほ"] },
    { consonant: "m", chars: ["ま", "み", "む", "め", "も"] },
    { consonant: "y", chars: ["や", null, "ゆ", null, "よ"] },
    { consonant: "r", chars: ["ら", "り", "る", "れ", "ろ"] },
    { consonant: "w", chars: ["わ", null, null, null, "を"] },
    { consonant: null, chars: [null, null, null, null, "ん"] },
    { consonant: "g", chars: ["が", "ぎ", "ぐ", "げ", "ご"] },
    { consonant: "z", chars: ["ざ", "じ", "ず", "ぜ", "ぞ"] },
    { consonant: "d", chars: ["だ", "ぢ", "づ", "で", "ど"] },
    { consonant: "b", chars: ["ば", "び", "ぶ", "べ", "ぼ"] },
    { consonant: "p", chars: ["ぱ", "ぴ", "ぷ", "ぺ", "ぽ"] },
  ],
  symbols: [
    { char: "あ", romaji: "a", set: "base", group: "Vowels" },
    { char: "い", romaji: "i", set: "base", group: "Vowels" },
    { char: "う", romaji: "u", set: "base", group: "Vowels" },
    { char: "え", romaji: "e", set: "base", group: "Vowels" },
    { char: "お", romaji: "o", set: "base", group: "Vowels" },
    { char: "か", romaji: "ka", set: "base", group: "K" },
    { char: "き", romaji: "ki", set: "base", group: "K" },
    { char: "く", romaji: "ku", set: "base", group: "K" },
    { char: "け", romaji: "ke", set: "base", group: "K" },
    { char: "こ", romaji: "ko", set: "base", group: "K" },
    { char: "さ", romaji: "sa", set: "base", group: "S" },
    { char: "し", romaji: "shi", set: "base", group: "S" },
    { char: "す", romaji: "su", set: "base", group: "S" },
    { char: "せ", romaji: "se", set: "base", group: "S" },
    { char: "そ", romaji: "so", set: "base", group: "S" },
    { char: "た", romaji: "ta", set: "base", group: "T" },
    { char: "ち", romaji: "chi", set: "base", group: "T" },
    { char: "つ", romaji: "tsu", set: "base", group: "T" },
    { char: "て", romaji: "te", set: "base", group: "T" },
    { char: "と", romaji: "to", set: "base", group: "T" },
    { char: "な", romaji: "na", set: "base", group: "N" },
    { char: "に", romaji: "ni", set: "base", group: "N" },
    { char: "ぬ", romaji: "nu", set: "base", group: "N" },
    { char: "ね", romaji: "ne", set: "base", group: "N" },
    { char: "の", romaji: "no", set: "base", group: "N" },
    { char: "は", romaji: "ha", set: "base", group: "H" },
    { char: "ひ", romaji: "hi", set: "base", group: "H" },
    { char: "ふ", romaji: "fu", set: "base", group: "H" },
    { char: "へ", romaji: "he", set: "base", group: "H" },
    { char: "ほ", romaji: "ho", set: "base", group: "H" },
    { char: "ま", romaji: "ma", set: "base", group: "M" },
    { char: "み", romaji: "mi", set: "base", group: "M" },
    { char: "む", romaji: "mu", set: "base", group: "M" },
    { char: "め", romaji: "me", set: "base", group: "M" },
    { char: "も", romaji: "mo", set: "base", group: "M" },
    { char: "や", romaji: "ya", set: "base", group: "Y" },
    { char: "ゆ", romaji: "yu", set: "base", group: "Y" },
    { char: "よ", romaji: "yo", set: "base", group: "Y" },
    { char: "ら", romaji: "ra", set: "base", group: "R" },
    { char: "り", romaji: "ri", set: "base", group: "R" },
    { char: "る", romaji: "ru", set: "base", group: "R" },
    { char: "れ", romaji: "re", set: "base", group: "R" },
    { char: "ろ", romaji: "ro", set: "base", group: "R" },
    { char: "わ", romaji: "wa", set: "base", group: "W" },
    { char: "を", romaji: "wo", set: "base", group: "W" },
    { char: "ん", romaji: "n", set: "base", group: "Others" },
    { char: "が", romaji: "ga", set: "dakuten", group: "G" },
    { char: "ぎ", romaji: "gi", set: "dakuten", group: "G" },
    { char: "ぐ", romaji: "gu", set: "dakuten", group: "G" },
    { char: "げ", romaji: "ge", set: "dakuten", group: "G" },
    { char: "ご", romaji: "go", set: "dakuten", group: "G" },
    { char: "ざ", romaji: "za", set: "dakuten", group: "Z" },
    { char: "じ", romaji: "ji", set: "dakuten", group: "Z" },
    { char: "ず", romaji: "zu", set: "dakuten", group: "Z" },
    { char: "ぜ", romaji: "ze", set: "dakuten", group: "Z" },
    { char: "ぞ", romaji: "zo", set: "dakuten", group: "Z" },
    { char: "だ", romaji: "da", set: "dakuten", group: "D" },
    { char: "ぢ", romaji: "ji", set: "dakuten", group: "D" },
    { char: "づ", romaji: "zu", set: "dakuten", group: "D" },
    { char: "で", romaji: "de", set: "dakuten", group: "D" },
    { char: "ど", romaji: "do", set: "dakuten", group: "D" },
    { char: "ば", romaji: "ba", set: "dakuten", group: "B" },
    { char: "び", romaji: "bi", set: "dakuten", group: "B" },
    { char: "ぶ", romaji: "bu", set: "dakuten", group: "B" },
    { char: "べ", romaji: "be", set: "dakuten", group: "B" },
    { char: "ぼ", romaji: "bo", set: "dakuten", group: "B" },
    { char: "ぱ", romaji: "pa", set: "dakuten", group: "P" },
    { char: "ぴ", romaji: "pi", set: "dakuten", group: "P" },
    { char: "ぷ", romaji: "pu", set: "dakuten", group: "P" },
    { char: "ぺ", romaji: "pe", set: "dakuten", group: "P" },
    { char: "ぽ", romaji: "po", set: "dakuten", group: "P" },
    { char: "きゃ", romaji: "kya", set: "double", group: "K" },
    { char: "きゅ", romaji: "kyu", set: "double", group: "K" },
    { char: "きょ", romaji: "kyo", set: "double", group: "K" },
    { char: "しゃ", romaji: "sha", set: "double", group: "S" },
    { char: "しゅ", romaji: "shu", set: "double", group: "S" },
    { char: "しょ", romaji: "sho", set: "double", group: "S" },
    { char: "ちゃ", romaji: "cha", set: "double", group: "T" },
    { char: "ちゅ", romaji: "chu", set: "double", group: "T" },
    { char: "ちょ", romaji: "cho", set: "double", group: "T" },
    { char: "にゃ", romaji: "nya", set: "double", group: "N" },
    { char: "にゅ", romaji: "nyu", set: "double", group: "N" },
    { char: "にょ", romaji: "nyo", set: "double", group: "N" },
    { char: "ひゃ", romaji: "hya", set: "double", group: "H" },
    { char: "ひゅ", romaji: "hyu", set: "double", group: "H" },
    { char: "ひょ", romaji: "hyo", set: "double", group: "H" },
    { char: "みゃ", romaji: "mya", set: "double", group: "M" },
    { char: "みゅ", romaji: "myu", set: "double", group: "M" },
    { char: "みょ", romaji: "myo", set: "double", group: "M" },
    { char: "りゃ", romaji: "rya", set: "double", group: "R" },
    { char: "りゅ", romaji: "ryu", set: "double", group: "R" },
    { char: "りょ", romaji: "ryo", set: "double", group: "R" },
    { char: "ぎゃ", romaji: "gya", set: "double", group: "G" },
    { char: "ぎゅ", romaji: "gyu", set: "double", group: "G" },
    { char: "ぎょ", romaji: "gyo", set: "double", group: "G" },
    { char: "じゃ", romaji: "ja", set: "double", group: "Z" },
    { char: "じゅ", romaji: "ju", set: "double", group: "Z" },
    { char: "じょ", romaji: "jo", set: "double", group: "Z" },
    { char: "ぢゃ", romaji: "ja", set: "double", group: "D" },
    { char: "ぢゅ", romaji: "ju", set: "double", group: "D" },
    { char: "ぢょ", romaji: "jo", set: "double", group: "D" },
    { char: "びゃ", romaji: "bya", set: "double", group: "B" },
    { char: "びゅ", romaji: "byu", set: "double", group: "B" },
    { char: "びょ", romaji: "byo", set: "double", group: "B" },
    { char: "ぴゃ", romaji: "pya", set: "double", group: "P" },
    { char: "ぴゅ", romaji: "pyu", set: "double", group: "P" },
    { char: "ぴょ", romaji: "pyo", set: "double", group: "P" },
  ],
  keyboard: {
    a: "あ",
    i: "い",
    u: "う",
    e: "え",
    o: "お",
    "a=": "ぁ",
    "i=": "ぃ",
    "u=": "ぅ",
    "e=": "ぇ",
    "o=": "ぉ",
    ka: "か",
    ki: "き",
    ku: "く",
    ke: "け",
    ko: "こ",
    sa: "さ",
    shi: "し",
    su: "す",
    se: "せ",
    so: "そ",
    ta: "た",
    chi: "ち",
    tsu: "つ",
    "tsu=": "っ",
    te: "て",
    to: "と",
    na: "な",
    ni: "に",
    nu: "ぬ",
    ne: "ね",
    no: "の",
    ha: "は",
    hi: "ひ",
    fu: "ふ",
    he: "へ",
    ho: "ほ",
    ma: "ま",
    mi: "み",
    mu: "む",
    me: "め",
    mo: "も",
    ya: "や",
    yu: "ゆ",
    yo: "よ",
    "ya=": "ゃ",
    "yu=": "ゅ",
    "yo=": "ょ",
    ra: "ら",
    ri: "り",
    ru: "る",
    re: "れ",
    ro: "ろ",
    wa: "わ",
    wo: "を",
    ga: "が",
    gi: "ぎ",
    gu: "ぐ",
    ge: "げ",
    go: "ご",
    za: "ざ",
    ji: "じ",
    zu: "ず",
    ze: "ぜ",
    zo: "ぞ",
    da: "だ",
    dji: "ぢ",
    dzu: "づ",
    de: "で",
    do: "ど",
    ba: "ば",
    bi: "び",
    bu: "ぶ",
    be: "べ",
    bo: "ぼ",
    pa: "ぱ",
    pi: "ぴ",
    pu: "ぷ",
    pe: "ぺ",
    po: "ぽ",
    n: "ん",
    v: "ゔ",
    "-": "ー",
    ",": "、",
    ".": "。",
  },
};

export const Katakana: Script = {
  chart: [
    { consonant: null, chars: ["ア", "イ", "ウ", "エ", "オ"] },
    { consonant: "k", chars: ["カ", "キ", "ク", "ケ", "コ"] },
    { consonant: "s", chars: ["サ", "シ", "ス", "セ", "ソ"] },
    { consonant: "t", chars: ["タ", "チ", "ツ", "テ", "ト"] },
    { consonant: "n", chars: ["ナ", "ニ", "ヌ", "ネ", "ノ"] },
    { consonant: "h", chars: ["ハ", "ヒ", "フ", "ヘ", "ホ"] },
    { consonant: "m", chars: ["マ", "ミ", "ム", "メ", "モ"] },
    { consonant: "y", chars: ["ヤ", null, "ユ", null, "ヨ"] },
    { consonant: "r", chars: ["ラ", "リ", "ル", "レ", "ロ"] },
    { consonant: "w", chars: ["ワ", null, null, null, "ヲ"] },
    { consonant: null, chars: [null, null, "ヴ", null, "ン"] },
    { consonant: "g", chars: ["ガ", "ギ", "グ", "ゲ", "ゴ"] },
    { consonant: "z", chars: ["ザ", "ジ", "ズ", "ゼ", "ゾ"] },
    { consonant: "d", chars: ["ダ", "ヂ", "ヅ", "デ", "ド"] },
    { consonant: "b", chars: ["バ", "ビ", "ブ", "ベ", "ボ"] },
    { consonant: "p", chars: ["パ", "ピ", "プ", "ペ", "ポ"] },
  ],
  symbols: [
    { char: "ア", romaji: "a", set: "base", group: "Vowels" },
    { char: "イ", romaji: "i", set: "base", group: "Vowels" },
    { char: "ウ", romaji: "u", set: "base", group: "Vowels" },
    { char: "エ", romaji: "e", set: "base", group: "Vowels" },
    { char: "オ", romaji: "o", set: "base", group: "Vowels" },
    { char: "カ", romaji: "ka", set: "base", group: "K" },
    { char: "キ", romaji: "ki", set: "base", group: "K" },
    { char: "ク", romaji: "ku", set: "base", group: "K" },
    { char: "ケ", romaji: "ke", set: "base", group: "K" },
    { char: "コ", romaji: "ko", set: "base", group: "K" },
    { char: "サ", romaji: "sa", set: "base", group: "S" },
    { char: "シ", romaji: "shi", set: "base", group: "S" },
    { char: "ス", romaji: "su", set: "base", group: "S" },
    { char: "セ", romaji: "se", set: "base", group: "S" },
    { char: "ソ", romaji: "so", set: "base", group: "S" },
    { char: "タ", romaji: "ta", set: "base", group: "T" },
    { char: "チ", romaji: "chi", set: "base", group: "T" },
    { char: "ツ", romaji: "tsu", set: "base", group: "T" },
    { char: "テ", romaji: "te", set: "base", group: "T" },
    { char: "ト", romaji: "to", set: "base", group: "T" },
    { char: "ナ", romaji: "na", set: "base", group: "N" },
    { char: "ニ", romaji: "ni", set: "base", group: "N" },
    { char: "ヌ", romaji: "nu", set: "base", group: "N" },
    { char: "ネ", romaji: "ne", set: "base", group: "N" },
    { char: "ノ", romaji: "no", set: "base", group: "N" },
    { char: "ハ", romaji: "ha", set: "base", group: "H" },
    { char: "ヒ", romaji: "hi", set: "base", group: "H" },
    { char: "フ", romaji: "fu", set: "base", group: "H" },
    { char: "ヘ", romaji: "he", set: "base", group: "H" },
    { char: "ホ", romaji: "ho", set: "base", group: "H" },
    { char: "マ", romaji: "ma", set: "base", group: "M" },
    { char: "ミ", romaji: "mi", set: "base", group: "M" },
    { char: "ム", romaji: "mu", set: "base", group: "M" },
    { char: "メ", romaji: "me", set: "base", group: "M" },
    { char: "モ", romaji: "mo", set: "base", group: "M" },
    { char: "ヤ", romaji: "ya", set: "base", group: "Y" },
    { char: "ユ", romaji: "yu", set: "base", group: "Y" },
    { char: "ヨ", romaji: "yo", set: "base", group: "Y" },
    { char: "ラ", romaji: "ra", set: "base", group: "R" },
    { char: "リ", romaji: "ri", set: "base", group: "R" },
    { char: "ル", romaji: "ru", set: "base", group: "R" },
    { char: "レ", romaji: "re", set: "base", group: "R" },
    { char: "ロ", romaji: "ro", set: "base", group: "R" },
    { char: "ワ", romaji: "wa", set: "base", group: "W" },
    { char: "ヲ", romaji: "wo", set: "base", group: "W" },
    { char: "ン", romaji: "n", set: "base", group: "Others" },
    { char: "ヴ", romaji: "v", set: "dakuten", group: "Others" },
    { char: "ガ", romaji: "ga", set: "dakuten", group: "G" },
    { char: "ギ", romaji: "gi", set: "dakuten", group: "G" },
    { char: "グ", romaji: "gu", set: "dakuten", group: "G" },
    { char: "ゲ", romaji: "ge", set: "dakuten", group: "G" },
    { char: "ゴ", romaji: "go", set: "dakuten", group: "G" },
    { char: "ザ", romaji: "za", set: "dakuten", group: "Z" },
    { char: "ジ", romaji: "ji", set: "dakuten", group: "Z" },
    { char: "ズ", romaji: "zu", set: "dakuten", group: "Z" },
    { char: "ゼ", romaji: "ze", set: "dakuten", group: "Z" },
    { char: "ゾ", romaji: "zo", set: "dakuten", group: "Z" },
    { char: "ダ", romaji: "da", set: "dakuten", group: "D" },
    { char: "ヂ", romaji: "ji", set: "dakuten", group: "D" },
    { char: "ヅ", romaji: "zu", set: "dakuten", group: "D" },
    { char: "デ", romaji: "de", set: "dakuten", group: "D" },
    { char: "ド", romaji: "do", set: "dakuten", group: "D" },
    { char: "バ", romaji: "ba", set: "dakuten", group: "B" },
    { char: "ビ", romaji: "bi", set: "dakuten", group: "B" },
    { char: "ブ", romaji: "bu", set: "dakuten", group: "B" },
    { char: "ベ", romaji: "be", set: "dakuten", group: "B" },
    { char: "ボ", romaji: "bo", set: "dakuten", group: "B" },
    { char: "パ", romaji: "pa", set: "dakuten", group: "P" },
    { char: "ピ", romaji: "pi", set: "dakuten", group: "P" },
    { char: "プ", romaji: "pu", set: "dakuten", group: "P" },
    { char: "ペ", romaji: "pe", set: "dakuten", group: "P" },
    { char: "ポ", romaji: "po", set: "dakuten", group: "P" },
    { char: "キャ", romaji: "kya", set: "double", group: "K" },
    { char: "キュ", romaji: "kyu", set: "double", group: "K" },
    { char: "キョ", romaji: "kyo", set: "double", group: "K" },
    { char: "シャ", romaji: "sha", set: "double", group: "S" },
    { char: "シュ", romaji: "shu", set: "double", group: "S" },
    { char: "ショ", romaji: "sho", set: "double", group: "S" },
    { char: "チャ", romaji: "cha", set: "double", group: "T" },
    { char: "チュ", romaji: "chu", set: "double", group: "T" },
    { char: "チョ", romaji: "cho", set: "double", group: "T" },
    { char: "ニャ", romaji: "nya", set: "double", group: "N" },
    { char: "ニュ", romaji: "nyu", set: "double", group: "N" },
    { char: "ニョ", romaji: "nyo", set: "double", group: "N" },
    { char: "ヒャ", romaji: "hya", set: "double", group: "H" },
    { char: "ヒュ", romaji: "hyu", set: "double", group: "H" },
    { char: "ヒョ", romaji: "hyo", set: "double", group: "H" },
    { char: "ミャ", romaji: "mya", set: "double", group: "M" },
    { char: "ミュ", romaji: "myu", set: "double", group: "M" },
    { char: "ミョ", romaji: "myo", set: "double", group: "M" },
    { char: "リャ", romaji: "rya", set: "double", group: "R" },
    { char: "リュ", romaji: "ryu", set: "double", group: "R" },
    { char: "リョ", romaji: "ryo", set: "double", group: "R" },
    { char: "ギャ", romaji: "gya", set: "double", group: "G" },
    { char: "ギュ", romaji: "gyu", set: "double", group: "G" },
    { char: "ギョ", romaji: "gyo", set: "double", group: "G" },
    { char: "ジャ", romaji: "ja", set: "double", group: "Z" },
    { char: "ジュ", romaji: "ju", set: "double", group: "Z" },
    { char: "ジョ", romaji: "jo", set: "double", group: "Z" },
    { char: "ヂャ", romaji: "ja", set: "double", group: "D" },
    { char: "ヂュ", romaji: "ju", set: "double", group: "D" },
    { char: "ヂョ", romaji: "jo", set: "double", group: "D" },
    { char: "ビャ", romaji: "bya", set: "double", group: "B" },
    { char: "ビュ", romaji: "byu", set: "double", group: "B" },
    { char: "ビョ", romaji: "byo", set: "double", group: "B" },
    { char: "ピャ", romaji: "pya", set: "double", group: "P" },
    { char: "ピュ", romaji: "pyu", set: "double", group: "P" },
    { char: "ピョ", romaji: "pyo", set: "double", group: "P" },
  ],
  keyboard: {
    a: "ア",
    i: "イ",
    u: "ウ",
    e: "エ",
    o: "オ",
    "a=": "ァ",
    "i=": "ィ",
    "u=": "ゥ",
    "e=": "ェ",
    "o=": "ォ",
    ka: "カ",
    ki: "キ",
    ku: "ク",
    ke: "ケ",
    ko: "コ",
    sa: "サ",
    shi: "シ",
    su: "ス",
    se: "セ",
    so: "ソ",
    ta: "タ",
    chi: "チ",
    tsu: "ツ",
    "tsu=": "ッ",
    te: "テ",
    to: "ト",
    na: "ナ",
    ni: "ニ",
    nu: "ヌ",
    ne: "ネ",
    no: "ノ",
    ha: "ハ",
    hi: "ヒ",
    fu: "フ",
    he: "ヘ",
    ho: "ホ",
    ma: "マ",
    mi: "ミ",
    mu: "ム",
    me: "メ",
    mo: "モ",
    ya: "ヤ",
    yu: "ユ",
    yo: "ヨ",
    "ya=": "ャ",
    "yu=": "ュ",
    "yo=": "ョ",
    ra: "ラ",
    ri: "リ",
    ru: "ル",
    re: "レ",
    ro: "ロ",
    wa: "ワ",
    wo: "ヲ",
    ga: "ガ",
    gi: "ギ",
    gu: "グ",
    ge: "ゲ",
    go: "ゴ",
    za: "ザ",
    ji: "ジ",
    zu: "ズ",
    ze: "ゼ",
    zo: "ゾ",
    da: "ダ",
    dji: "ヂ",
    dzu: "ヅ",
    de: "デ",
    do: "ド",
    ba: "バ",
    bi: "ビ",
    bu: "ブ",
    be: "ベ",
    bo: "ボ",
    pa: "パ",
    pi: "ピ",
    pu: "プ",
    pe: "ペ",
    po: "ポ",
    n: "ン",
    v: "ヴ",
    "-": "ー",
    ",": "、",
    ".": "。",
  },
};
